### ISSUE TITLE
iOS配置导航后，提示“无可用导航信息”是怎么回事呢？

### ISSUE THREAD

**Issue by fanshisha** [qunarcorp/imsdk-android#32]
部署完成后，iOS端配置导航，弹框提示“无可用导航信息”，是哪里出问题了？

**Comment by Lidalu** [comment]
亲，你的Startalk App没有开启数据流量权限吧，可以前往手机【设置】-【Startalk】-【无线数据】，打开数据流量权限开关。后续我们会对这块做优化。

另外，iOS的issue可以到 https://github.com/qunarcorp/imsdk-ios 提
