### ISSUE TITLE
会话页面点击右上角查看用户详情崩溃问题解决

### ISSUE THREAD

**Issue by jianibaobei** [qunarcorp/imsdk-android#36]
java.lang.UnsatisfiedLinkError: could find DSO to load: libreactnativejni.so

会话页面点击右上角查看用户详情崩溃问题解决方法：
app的 build.gradle中： 
     ndk {
            abiFilters "armeabi"  此处最好只保留这一个
        }
        packagingOptions {
            exclude "lib/arm64-v8a/librealm-jni.so"
        }

**Comment by jianibaobei** [comment]
编辑

**Comment by froyomu** [comment]
因为ReactNative不支持64位所以在
app的 build.gradle中添加：
packagingOptions {
exclude "lib/arm64-v8a/librealm-jni.so"
}
