### ISSUE TITLE
单聊变群，添加群成员，删除群成员，单聊成员点击崩溃

### ISSUE THREAD

**Issue by jianibaobei** [qunarcorp/imsdk-android#39]
1、会话列表，打开一个单聊
2、此时点击右上角查看聊天信息，点击页面中+号按钮
3、在添加群成员页面，此时可以看到单聊用户，点击该用户，闪退（点击表示删除操作，此时不能删除该单聊用户才正确）
4、添加多个成员，删除没问题，但是删除到该单聊成员时崩溃

**Comment by froyomu** [comment]
Fixed in version 3.0.2
